spring:
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /springboot1
model:
  p1: 网格
management:
  endpoints:
    web:
      exposure:
        include: health
---
server:
  port: 8085
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod